apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
    interval: 5m
    chart:
        spec:
            chart: nginx
            version: "15.0.0"
            sourceRef:
                kind: HelmRepository
                name: bitnami
                namespace: flux-system
            interval: 1m
    values:
        service:
            type: ClusterIP